app/__init__.py
from flask import Flask
from app.routes import core_bp, app_bp


def create_app() -> Flask:
    app = Flask(__name__)
    app.register_blueprint(app_bp)
    app.register_blueprint(core_bp)
    return app

app/config/__init__.py
from .paths import Paths

app/routes/__init__.py
from .core import core_bp
from .api import app_bp

app/routes/api.py
from flask import Blueprint, render_template, redirect

app_bp = Blueprint("api", __name__)


@app_bp.route("/")
def index():
    return redirect("/home")


@app_bp.errorhandler(404)
def page_not_found():
    return render_template("404.html"), 404


@app_bp.route("/home/", methods=["GET", "POST"])
def home():
    return render_template("home.html"), 200


@app_bp.route("/model/", methods=["GET", "POST"])
def model():
    return render_template("model.html"), 200


@app_bp.route("/model/predict/", methods=["GET", "POST"])
def predict():
    return render_template("predict.html"), 200


@app_bp.route("/about/", methods=["GET", "POST"])
def about():
    return render_template("about.html"), 200

app/routes/core.py
from flask import (
    Blueprint,
    send_from_directory,
    request,
    render_template,
    redirect,
    url_for,
)
import pandas as pd

from app.utils import get_prediction

UPLOAD_PATH = "uploads"
ALLOWED_FILE_TYPES = ["csv"]

core_bp = Blueprint("core", __name__)


@core_bp.post("/download/")
def download_csv_template():
    return send_from_directory(
        UPLOAD_PATH, "aqi_input_template.csv", as_attachment=True
    )


@core_bp.post("/upload/")
def upload():
    data_path = request.files["csv"]
    if data_path and data_path.filename.split(".")[1] in ALLOWED_FILE_TYPES:
        df = pd.read_csv(data_path)
        prediction = list(get_prediction(df))
        return render_template("predict.html", prediction=prediction), 200
    return redirect(url_for("api.predict"))

app/utils/__init__.py
from .model_prediction import get_prediction

app/templates/about.html
{% extends 'base.html' %}
{% block title %} About  {% endblock %}
{% block heading %}About This Project {% endblock %}
{% block content %}
<p>Air pollution is an invisible but serious challenge that affects millions globally. This app was created to bridge the gap between data and actionable insights, empowering users to make informed choices about their health and environment.</p>

<table>
   <tr>
      <td style="text-align: center;"><h3>Technologies Used</h3></td>
      <td>
         <li>Backend: Flask</li>
         <li>Frontend: HTML, CSS, JS, Jinja Templates</li>
         <li>ML Models: Linear Regression</li>
         <li>Data Visualization: Matplotlib, seaborn</li>
      </td>
   </tr>
</table>

<p>Curious to explore how this app works under the hood? Visit my <a href="https://github.com/adnaaaen/air-quality-index-analysis">Github repository</a>to view the source code, contribute to the project, or use it as inspiration for your own ideas.🌍✨</p>

{% endblock %}
{% block footer %}
<p style="font-size: 12px">
  Made by
  <a href="https://linktr.ee/adnaaaen" style="font-size: 14px">Adnan</a>
</p>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
    />
    <title>{% block title %} {% endblock %} | AQI</title>
  </head>
  <body>
    <header class="nav-bar">
      <div>
        <p>🔍</p>
      </div>
      <div>
        <nav>
          <a
            href="{{ url_for('api.home') }}"
            class="nav-link {{ 'active' if request.path == '/home/' else '' }}"
            >home</a
          >
          <a
            href="{{ url_for('api.model') }}"
            class="nav-link {{ 'active' if request.path == '/model/' else '' }}"
            >model</a
          >
          <a
            href="{{ url_for('api.about') }}"
            class="nav-link {{ 'active' if request.path == '/about/' else '' }}"
            >about</a
          >
        </nav>
      </div>
    </header>
    <div class="page-title">{% block heading %}{% endblock %}</div>
    <section class="content">{% block content %}{% endblock %}</section>
    <footer>{% block footer %}{% endblock %}</footer>
  </body>
</html>

app/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
<div class="space-between-container">
    <div class="container">
        <h3>What is AQI (Air Quality Index)?</h3>
        <p>The Air Quality Index (AQI) is a measure used to communicate how polluted the air currently is or how polluted it is forecast to become. It is designed to inform the public about air quality and its potential impact on health.</p>
    </div>
    <div class="container">
    <img src="{{ url_for('static', filename='images/img-1.jpg') }}" alt="img" class="image-container">
    </div>
</div>
<div class="container">
<table>
    <tr>
        <th colspan="6">Categories</th>
    </tr>
    <tr>
        <td>Good (0–50)</td>
        <td>Moderate (51–100)</td>
        <td>Unhealthy for Sensitive Groups (101–150)</td>
        <td>Unhealthy (151–200)</td>
        <td>Very Unhealthy (201–300)</td>
        <td>Hazardous (301–500)</td>
    </tr>
</table>
</div>
{% endblock %}

app/templates/model.html
{% extends 'base.html' %}
{% block title %} Model {% endblock %}
{% block heading %}Model{% endblock %}
{% block content %}
<div class="container" style="align-items: end;">
   <form action="{{ url_for('api.predict') }}" method="get">
      <input type="submit" value="Make Prediction" class="primary-button">
   </form>
</div>

<div class="space-between-container">
    <div class="container">
        <h3>Overview</h3>
            <ul>
                <li>
                    Model : <strong>Random Forest Regressor</strong>
                </li>
                <li>
                    Type of Model : <strong>Supervised (regression)</strong>
                </li>
                <li>
                    Best Params: 
                    <ul>
                        <li><strong>max_depth</strong>: 15</li>
                        <li>
                            <strong>min_samples_leaf</strong>: 2
                        </li>
                        <li>
                            <strong>min_samples_split</strong>: 2
                        </li>
                        <li>
                            <strong>n_estimators</strong>: 100 
                        </li>
                    </ul>
            </ul>
    </div>
    <div class="container">
            <h3>Evaluation Metrics</h3>
            <table>
                <tr>
                    <th></th>
                    <th>MAE</th>
                    <th>MSE</th>
                    <th>R² Score</th>
                </tr>
                <tr>
                    <th>Train Set</th>
                    <td>0.1856</td>
                    <td>0.2063</td>
                    <td>0.8521</td>
                </tr>
                <tr>
                    <th>Test Set</th>
                    <td>0.0693</td>
                    <td>0.0852</td>
                    <td>0.8180</td>
                </tr>
            </table>
    </div>
</div>
{% endblock %}

app/templates/predict.html
{% extends 'base.html' %}
{% block title %} Predict {% endblock %}
{% block heading %} Predict AQI {% endblock %}
{% block content %}

<div class="container">
    <form action="{{ url_for('core.download_csv_template') }}" method="post">
        <label for="">Download the CSV template file to view the required features. After downloading, fill in the required inputs directly in the file and upload it back once completed.</label>
        <input type="submit" value="Download" class="primary-button">
    </form>
</div>

<div class="container" style="border: 1px solid rgb(213, 211, 211); border-radius: 3px; padding: 20px;">
    <form action="{{ url_for('core.upload') }}" method="post" enctype="multipart/form-data" class="space-between-container">
        <div>
            <label for="csv">Choose csv file to upload </label>
            <input type="file" name="csv" id="csv">
        </div>
        <input type="submit" value="Get Predict" class="primary-button">
    </form>
</div>

<div class="container" style="align-items: center;">
    {% if prediction %}
    <table>
        <tr>
            <th colspan="2">Predicted AQI</th>
        </tr>
        {% for index, each in prediction %}
        <tr> 
        <td>{{ index }}</td>
        <td>{{ each}}</td>
        </tr>
        {% endfor %}

    </table>
    {% else %}
    <p class="page-placeholder">upload file to get prediction :)</p>
    {% endif %}
</div>
{% endblock %}